### ISSUE TITLE
UI/UX + custom shape option

### ISSUE THREAD

**Issue by matejbolta** [Mankifg/mbldscramb#1]
When you input the *Number of cubes*, the fields for *Cubes per page*, *Pages*, and *Add* are automatically populated. However, these fields remain editable, not just displayed as static numbers.

Since the actual number and layout of scrambles depend only on the right three fields (*Cubes per page*, *Pages*, and *Add*), a more intuitive implementation would remove these fields and handle the calculations solely in the backend.

An even better approach could be:

If the user prefers a custom layout instead of a square shape, which is often the case, provide just one input for the *Number of cubes*. Additionally, include a checkbox for either *Square shape* or *Custom shape*.

If *Custom shape* is selected, display an additional input for *Cubes per page* (as *Number of pages* and *Add* can be automatically derived from *Number of cubes* and *Cubes per page*).

This approach supports both square and custom shapes with better UX

**Comment by Mankifg** [comment]
on TODO

**Comment by Mankifg** [comment]
shoud be fixed
